Feature/#7
wafflestudio18-5/team8-android pull request #19
Opened 2020-12-01 16:17 UTC by jusjinuk

This PR will resolve #7.

- 아이폰 앱 기준으로 clone 하여 MainActivity 안의 fragment들을 viewpager로 구현. (안드로이드 앱은 Navigation graph로 구현해야 하는 것으로 보임)
- gradle에서 single dex file 이슈가 있어 build.gradle file에 관련 line 추가(자세한 내용은 [링크](https://velog.io/@jojo_devstory/Android-Cannot-fit-requested-classes-in-a-single-dex-file-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95-%EB%B0%8F-%EC%9B%90%EC%9D%B8-%EB%B6%84%EC%84%9D) 참고)

- 추가로 코드에 궁금한 점 있거나 리뷰할 점 있으면 달아주세요!

2020-12-02 05:13 UTC, jusjinuk reviewed
보충 설명 필요할만한 곳 comment 붙입니다!

2020-12-02 05:13 UTC, jusjinuk commented on PodoMarket/.idea/codeStyles/Project.xml
> +</component>
reformat할 때 쓰이는 codestyle로 보입니다. [링크](https://stackoverflow.com/questions/50618188/what-is-codestyleconfig-xml-file-in-codestyles-of-idea-folder)를 참고하시면 될 것 같습니다!

2020-12-02 05:13 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainActivity.kt
> +            pager.isUserInputEnabled = false
viewpager로 구현했지만 user가 직접 페이지를 넘기지 못하도록 설정했습니다(bottom navigation으로만 바꿀 수 있게).

2020-12-02 05:13 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainActivity.kt
> +                    R.id.my_page_fragment -> pager.setCurrentItem(MYPAGE, false)
넘겨지는 애니메이션 없도록 `setCurrentItem` 이용했습니다.

2020-12-02 10:25 UTC, sanggggg requested changes

2020-12-02 10:25 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainPagerAdapter.kt
> +}
else 를 고려하지 않고도 안전하게 처리할 수 있게 enum class를 사용합시다
```kotlin
enum class FragmentConst {
    PRODUCT,
    ARTICLE,
    CHAT,
    MYPAGE
}
```

2020-12-02 10:25 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainPagerAdapter.kt
> +}
[nitpick] MainPageType, MainFragmentType 같은 클래스명이 더 적절하지 않을까요?

2020-12-02 10:25 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
```kotlin
private val binding: ActivityMainBinding by lazy { DataBindingUtil.setContentView(this, R.layout.activity_main) }
```
로 안전하게 val 로 binding 처리하면 좋을 것 같아요

2020-12-02 12:16 UTC, jusjinuk reviewed
@sanggggg 바쁘신 와중에 리뷰 감사드립니다~!!! 👍 👍 
코드 수정하면서 궁금했던 부분 간단히 표시합니다!!

2020-12-02 12:16 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainPagerAdapter.kt
> +        fun getByValue(value: Int) = VALUES.first { it.value == value }
`createFragment`가 Int 변수 `position`을 받아 [링크](https://stackoverflow.com/questions/53523948/how-do-i-create-an-enum-from-a-int-in-kotlin/53524077) 참고하여 바꾸었습니다. 이렇게 된다면 기존에 `when`에서 else로 분기되어 처리되던 error가 여기서 처리되는데 (매칭되는 value가 없는 경우) 이런 패턴이 더 바람직한가요?

2020-12-03 03:36 UTC, sanggggg approved these changes

2020-12-03 03:36 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/MainPagerAdapter.kt
> +        fun getByValue(value: Int) = VALUES.first { it.value == value }
아 createFragment 에서 index 에 대응되는 `Int` 가 필요한 상황이었네요 제대로 살펴보지 못하고 enum class 을 추천드렸습니다.
> 물론 이렇게 특정 값과 연결할 필요가 없다면 enum 을 써서 안전하게 else 처리하는 걸 추천드립니다.
이런 상황이라면 이전의 FragmentConst 를 사용해도 괜찮을거 같아요(sorry)

2020-12-03 14:46 UTC, merged