Feature/#16
wafflestudio18-5/team8-android pull request #21
Opened 2020-12-05 06:33 UTC by flux1126

This PR will resolve #16.

2020-12-05 06:39 UTC, sanggggg approved these changes

2020-12-05 06:39 UTC, sanggggg commented on PodoMarket/app/src/main/res/layout/activity_chat_room.xml
> +        </LinearLayout>
[nitpick] + 정보전달?
뷰 계층이 깊어질 때 성능이 떨어지게 되는데 ConstraintLayout 은 뷰를 자유자재로 배치할 수 있어 이런 뷰 계층을 얉게 해 주어 성능을 최적화 할 수 있습니다.

[참고](https://abandonia.tistory.com/1)

2020-12-05 09:15 UTC, jusjinuk requested changes
빠뜨린 부분이 조금씩 있으셔서 실행해보지는 못했는데 layout 미리보기로 보았을 때는 디자인은 좋아보입니다! 빠뜨려서 error 나는 경우 없도록 AVD로 한 번씩 돌려주시면 감사드리겠습니다! AVD 통하여 확인하고자 하는 목적으로 starting point를 (임시적으로) 편집 중인 Activity로 바꾸고 싶은 경우 `AndroidManifest.xml` 파일에서 MainActivity 안에 있는 intent filter를 아래와 같이 옮기면 됩니다.
```
        <activity android:name="편집중인 Activity 위치">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

2020-12-05 09:15 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/chat/ChatRoomActivity.kt
> +    }
#20 PR comment와 마찬가지로 import line들 추가해주세요!!

2020-12-05 09:15 UTC, jusjinuk commented on PodoMarket/app/src/main/res/drawable/border_round_loyal_blue.xml
> +        android:color="@color/loyal_blue" >
우선 이 브랜치에서는 values/colors.xml에 color값을 추가하지 않으셔서 에러가 뜹니다. 이 브랜치에서도 추가해주시면 감사드리겠습니다!

[nitpick] 그리고 혹시 royal_blue 아닌가요?? 오타인 것 같습니다.

2020-12-05 09:15 UTC, jusjinuk commented on PodoMarket/app/src/main/res/drawable/borduer_round_gray.xml
> +        android:color="@color/light_gray" >
마찬가지로 color value들 추가 부탁드립니다!!

2020-12-05 09:27 UTC, flux1126 commented on PodoMarket/app/src/main/res/layout/activity_chat_room.xml
> +        </LinearLayout>
아하.. 가독성 뿐만 아니라 성능에도 직접 영향을 미치는군요. 이번 기회에 아예 ConstraintLayout으로 갈아타야겠습니다.

2020-12-05 09:28 UTC, flux1126 commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/chat/ChatRoomActivity.kt
> +    }
테스트 관련 꿀팁 감사합니다 👍 다음 PR부터는 꼭 한번씩 돌려보고 올리겠습니다 ㅎㅎ

2020-12-05 09:29 UTC, flux1126 commented on PodoMarket/app/src/main/res/drawable/border_round_loyal_blue.xml
> +        android:color="@color/loyal_blue" >
모든 브랜치에 해당 컬러를 우선 추가하겠습니다! 아 그리고 royal_blue가 맞는 것 같습니다! 제 하찮은 영어실력이 이렇게 공개되다니...

2020-12-05 09:54 UTC, jusjinuk commented on PodoMarket/app/src/main/res/drawable/border_round_royal_blue.xml
> +        android:color="@color/loyal_blue" >
```suggestion
        android:color="@color/royal_blue" >
```

2020-12-22 14:03 UTC, jusjinuk approved these changes
@flux1126 얘도 마찬가지로 intent 관련 함수 추가해주시면 감사드릴 것 같습니다!! 일단 Approve하니 추가하고 merge 부탁드려요!!

2020-12-25 17:15 UTC, merged