Add AppBar to ProfileActivity
wafflestudio18-5/team8-android pull request #26
Opened 2020-12-22 11:24 UTC by flux1126

This PR will resolve #24.

2020-12-22 12:19 UTC, jusjinuk requested changes
수고하셨습니다!! 수정 필요해보이는 부분 comment 달아놓았습니다!!

2020-12-22 12:19 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/ProfileActivity.kt
>  class ProfileActivity : AppCompatActivity() {
navigation에 종속된 fragment가 아닌 외부 Activity들은 그 안에 해당 activity를 호출하는 Intent를 반환하는 function을 작성해야 할 것 같습니다. 참고가 되실까해서 제가 이전 프로젝트에서 작성했던 코드 첨부합니다. 비슷하게 추가해주시면 될 것 같습니다.
```kotlin
// DetailSeminarActivity 내부
    companion object {
        const val SEMINAR_ID = "seminar_id"

        fun intentWithSeminarId(context: Context, id: Int): Intent =
            Intent(context, DetailSeminarActivity::class.java)
                .apply { putExtra(SEMINAR_ID, id) }
    }
```
이렇게 해두면 다른 Activity에서
```kotlin
startActivity(DetailSeminarActivity.intentWithSeminarId(this, it))
```
만을 이용하여 해당 activity를 호출할 수 있게 됩니다. 이 경우에서는 전달하는 `putExtra`, `getExtra`가 없으니 그런 것 없이 더 간단하게 구현해놓아도 될 것 같습니다.

2020-12-22 12:19 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/ProfileActivity.kt
> +                }
아이폰 앱 기준으로는 좌측 상단에 navigateUp button이 존재하는데 혹시 안드로이드는 다른가요? 만약 존재한다면 추가하는 것이 좋을 것 같습니다. 아래 코드는 `ProductCategoryFragment` 중에서 가져온 코드인데 참고하시면 될 것 같습니다.
```kotlin
            toolBar.also { tb ->
                tb.setNavigationIcon(R.drawable.ic_baseline_arrow_back_24)
                tb.setNavigationOnClickListener {
                    findNavController().navigateUp() 
                    // 이 경우에는 이 자리에 activity를 끝내는 코드가 들어가야 할 것 같습니다.
                    // 제 기억으로는 finish()였던 것 같은데 확실한 건 확인해보시면 될 것 같습니다.
                }
            }
```

2020-12-22 12:19 UTC, jusjinuk commented on PodoMarket/app/src/main/res/layout/activity_profile.xml
> +                <TextView
아이폰 앱 기준으로는 상단 toolbar의 글자 "프로필"이 가운데에 있는데 안드로이드도 마찬가지인가요? 만약 그렇다면 `android:layout_gravity="center"`를 추가해야 할 것 같습니다.

2020-12-22 13:06 UTC, flux1126 commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/ProfileActivity.kt
> +                }
찾아보니 activity를 종료할 때,
(1) finish()를 쓰는 경우
- 단순히 activity를 종료할 때
- intent의 putExtra()를 이용해야 할 때
(2) onBackPressed를 쓰는 경우
- activity 종료와 함께 특정한 작업을 해야 할 경우 해당 함수를 override해서 사용

위와 같은 것 같습니다 👍

2020-12-22 13:34 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/ProfileActivity.kt
> +                }
@flux1126 우선 다른 요소들 수정 감사드립니다!! 이 부분은 `menu`의 `item`으로 추가하는 방법으로 구현하신 것 같은데 클릭이 이벤트 호출은 제대로 되지만 아래 사진과 같이 우측 상단에 뒤로가기 버튼이 만들어집니다.
![image](https://user-images.githubusercontent.com/58197958/102893344-c8419a80-44a4-11eb-9d8a-da0f2b4d72b7.png)
실제 앱 기준으로는 아래와 같이 좌측 상단에 뒤로가기 버튼이 떠서
![당근마켓2](https://user-images.githubusercontent.com/58197958/102893989-c4624800-44a5-11eb-91f4-551024832cfb.png)
혹시 의도하신 동작이신가요? 만약 아니라면 위의 예시처럼 toolbar의 `setNavigationIcon`과 `setNavigationOnClickListener`를 사용하면 될 것 같습니다. 수고해주셔서 감사합니다!!

2020-12-26 04:08 UTC, jusjinuk approved these changes

2020-12-26 04:51 UTC, merged