init fragment_my_page.xml
wafflestudio18-5/team8-android pull request #3
Opened 2020-11-23 13:58 UTC by flux1126

init activate_main.xml
make button_white_gray.xml

2020-11-23 14:34 UTC, jusjinuk commented
다음 PR부터는 아래 순서를 지키면서 PR 날려주시면 감사드리겠습니다! 저도 이번에 알게 되었는데 이 순서를 지키면서 해야 project board에서 tracking도 잘 되고 협업하기 편한 것 같더라고요!

1. 필요한 기능이 적힌 issue를 적절한 제목으로 올림 ('[Android]'를 제목의 앞에 붙여서)
2. 해당 issue 페이지 우측에 Projects 탭에서 톱니바퀴를 눌러서 team8 project board 추가
3. 해당 issue의 번호가 명시된 이름으로 branch를 팜.(예시: issue의 번호가 #1일 때 branch 이름: feature/#1)
4. 기능 작업 후 브랜치에 커밋
5. PR을 날릴 때 PR 내용에 "This PR will resolve #<이슈번호> issue." 포함해주세요! (이러면 issue와 PR이 연결되어서 PR이 머지될 때 issue 자동으로 닫힘)
6. issue와 마찬가지로 PR 페이지 우측에 Projects 탭에서 톱니바퀴를 눌러서 team8 project board 추가

위 방법이 프로젝트 보드에서 이슈 진행 상황을 모니터링 할 수 있게 되어 (이슈도 따라갈 수 있고) 좋은 것 같더라고요.

2020-11-23 21:34 UTC, dodo4114 requested changes
- 이슈 컨트롤은 resolve/fix/close 다 가능합니다.
- 작업 하신 내용이 2개로 나뉘는 것 같은데, commit 분리해주세요.

2020-11-25 09:35 UTC, flux1126 commented
제대로된 협업이 처음이라 많이 미숙하네요.
두 분이 너무 열심히 가르쳐주려서 감사할 따름입니다.
이 PR도 가르쳐주긴데로 수정할 수 있는 한 수정해보겠습니다.

@dodo4114 혹시 Commit을 분리하는 건 어떻게 해야 하는지 작은 힌트를 얻을 수 있을까요?

2020-11-28 04:29 UTC, closed without merging

2020-11-28 04:29 UTC, flux1126 commented
Not yet

2020-11-29 13:11 UTC, dodo4114 commented
`git reset`이 도움이 될 것 같습니다