Feature/#13
wafflestudio18-5/team8-android pull request #30
Opened 2020-12-26 17:19 UTC by jusjinuk

resolve #13.

2020-12-27 07:26 UTC, sanggggg requested changes

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/build.gradle
> +            storePassword 'podomarket'
ㅋㅋㅋㅋㅋ... 보안상 local.properties 로 패스워드를 빼는게 좋을 것 같습니다!
> 물론 토이플젝에서 그럴 필요는 없겠지만 다음부터는!
> [참고](https://blog.mindorks.com/using-local-properties-file-to-avoid-api-keys-check-in-into-version-control-system)

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/build.gradle
> +    implementation "com.kakao.sdk:v2-user:2.2.0"
카카오에서 rxjava 2 를 사용하기에 나중에 코드 짤 때 rxjava 3 와 섞여 사용될 가능성이 있어보이니 수정 or 조심해서 작성해주세요

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/PodoMarketApplication.kt
> +        KakaoSdk.init(this, "060207fa3b8cf68c8427a40c814f7643")
local.properties 로 빼거나 secrets.xml 로 빼고 깃에 업데이트 하지 않도록 하는게 좋을 거 같습니다.

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/di/NetworkModule.kt
> +}
질문) 아래쪽에서 작성한 프로바이더 들은 실제 서버 연결 후 모듈에 넣을 예정인가요?

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +                        Log.e("SettingFragment", error.toString())
Timber 를 사용하면 더 쉽게 (TAG) 없이 로그를 남길 수 있습니다.
[timber](https://github.com/JakeWharton/timber)

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +                    } ?: kotlin.run {
[nitpick]
`kotlin.` 을 지워도 되지 않나요?

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +                    } ?: kotlin.run {
이렇게 될 경우 `error?.run {` 에서 반환된 값이 null 이라면 error?.run 도 실행되고, 뒤쪽의 startLoginActivity 도 실행되는 문제가 발생합니다.

여기선 Log.e 의 반환값에 따라 두 블럭이 모두 실행될 수도 있습니다. error 가 null 인 경우만 뒤의 문장을 실행하고 싶다면, 아래와 같이 해야할 것 같네요 (+ 구지 run 일 필요가 있을까요?)

```kotlin
error?.also { error ->
    Log.e(...)
} ?: run {
    startLoginActivity()
}
```

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +    }
이런 코드는 LoginActivity 의 companion object 에 쓰는게 적절해 보입니다.

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/LoginActivity.kt
> +    }
companion object 는 컨벤션 상 맨 아래로

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/LoginActivity.kt
> +    val binding: ActivityLoginBinding by lazy {
[nitpick]
private?

2020-12-27 07:26 UTC, sanggggg commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/user/LoginActivity.kt
> +                    }
구지 single.just 를 쓸 필요가 없어보입니다.
```kotlin
if (LoginClient.instance.isKakaoTalkLoginAvailable(this@LoginActivity)) {
    LoginClient.rx.loginWithKakaoTalk(this@LoginActivity)
} else {
    LoginClient.rx.loginWithKakaoAccount(this@LoginActivity)
}.observeOn()
//...
```

2020-12-27 19:48 UTC, jusjinuk commented on PodoMarket/app/build.gradle
> +            storePassword 'podomarket'
관련 가이드 첨부 감사드립니다ㅠㅠ 이슈 고쳤습니다! 더 유의하도록 하겠습니다.

2020-12-27 19:49 UTC, jusjinuk commented on PodoMarket/app/build.gradle
> +    implementation "com.kakao.sdk:v2-user:2.2.0"
이 부분은 kakao에서 지원하는 범위라 어쩔 수 없어서 조심해서 사용하되 너무 헷갈린다면 저희 project의 rx를 2로 다운그레이드하도록 하겠습니다! 일단은 조심해서 사용하는 방향으로 생각하고 있긴 합니다!

2020-12-27 19:50 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/di/NetworkModule.kt
> +}
넵 그럴 예정입니다!

2020-12-27 19:51 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +                        Log.e("SettingFragment", error.toString())
Timber [반영](https://github.com/wafflestudio18-5/team8-android/pull/30/commits/1b3543c1c904071c9a3ebd08bae341aff6981b86)하였습니다! 감사합니다.

2020-12-27 19:53 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +                    } ?: kotlin.run {
항상 [이 글](https://medium.com/@limgyumin/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%98-apply-with-let-also-run-%EC%9D%80-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EA%B0%80-4a517292df29) 보면서 scoping fun 잘 사용해보자 하는데 자꾸 헷갈리네요ㅠ 큰 실수 지적해주셔서 감사드립니다!

2020-12-27 19:56 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/ui/main/mypage/SettingFragment.kt
> +    }
@sanggggg `startActivity` 함수를 전부 넣는 것은 투머치인 것 같아서(호출하는 쪽에서 커스텀할 여지가 없는 느낌?) `intent` 함수만 집어넣었는데 어떻게 생각하시나요? `startActivity`와 `finish`까지 하나의 함수로 만들어서 넣는 게 나아보이시는지 궁금합니다. 해당 [커밋](https://github.com/wafflestudio18-5/team8-android/pull/30/commits/f49b1209ceced8368209b94173bae2b019a39996)입니다.

2020-12-27 20:00 UTC, jusjinuk commented
@sanggggg 정성어린 리뷰 감사드립니다!! 👍👍 
지적해주신 부분 수정하고 해당 comment 밑에 설명도 달았습니다!! 확인해주시면 감사드리겠습니다.

2020-12-28 15:36 UTC, flux1126 approved these changes
정말 수고 많으셨습니다. 하나라도 도움이 될 만한 내용을 드리고 싶어서 꼼꼼히 읽어봤는데, 제 지식이 미약하여 보충할 만한 부분을 찾을 수 없네요. 오히려 PM님 리뷰를 보고 저도 같이 배워가는 느낌입니다. 저도 PM님처럼 좋은 리뷰를 남길 수 있게 더 열심히 노력하겠습니다. 고생 많으셨습니다 👍

2020-12-28 16:35 UTC, sanggggg approved these changes

2020-12-28 16:39 UTC, merged