SharedPreference를 이용한 User Info 저장
wafflestudio18-5/team8-android pull request #50
Opened 2021-01-03 18:11 UTC by flux1126

SharedPreference를 Application 전역을 범위로 사용하는데 익숙하지 않아서 그런지 쉬운 내용인데 한참 헤매고 있네요.

로그인 시,  User 정보를 SharedPreference에 Save()하고
User 정보가 필요할 시, SharedPreference에서 Load()하고
로그아웃 시, SharedPreference에서 Delete()하고 싶습니다.

오프라인 상태에서도 MyPage 등을 위해 필요한 내용은 표시될 수 있게 user_id 뿐만 아니라 자기 자신에 대한 모든 정보를 저장하려고 합니다.
이때 UserInfo 클래스를 만들고 UserDto를 받아 동작하는 이러한 코드가 올바른 구현인가요? 제 생각에 save()나 load() 함수의 context 인자에 applicationContext만 넣어주면 Application 전역에서 돌아가기는 할 거 같습니다. 그런데 구현할수록 디자인 패턴이 깔끔하지 못하다는 생각이 들어 이렇게 Review 부탁드립니다.

2021-01-04 12:14 UTC, sanggggg commented
1. 우선 이런 구현 자체는 문제가 없습니다. 다만 `UserInfo(applicationContext)` 를 매번 만들고 있지말고 koin module 에 추가해서 injection 받아 사용하는게 적절할 것 같습니다. 이런식으로 User 에 대한 관리는 보통 network api call 과 같이 이뤄지기 때문에 이런 코드는 UserRepository 가 있다면 그쪽에 추가되는게 좋아 보입니다.

2. 그리고 저런 식으로 모든 값을 일일이 저장하지 않고도 @Parcelize, @Parcelable 을 사용하면 훨씬 쉽게 데이터를 직렬화 시켜 저장할 수 있습니다. (물론 SharedPreference 에 한번에 집어넣을 수도 있고요) 한번 확인해보세요.

2021-01-04 15:11 UTC, jusjinuk reviewed
늦은 리뷰 사과드립니다ㅠㅠ 저도 PM님 말씀대로 Repository의 함수로 저장하는 것 좋은 생각인 것 같네요!

2021-01-04 15:11 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/model/UserInfo.kt
> +class UserInfo(context: Context) {
sharedPreference는 제가 koin module에 provider를 추가해놓아서 DI를 사용하여 주입받는 것이 어떨까 싶네요. 꼭 다른 preference file name으로 저장하고 싶으신게 아니면요.

2021-01-04 15:11 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/model/UserInfo.kt
> +            editor.putInt(USER_ID, userDto.user_id)
전 사실 SharedPreference에 Gson의 toJson, fromJson을 사용하여 객체를 json string 형태로 저장하면 좋겠다 생각하고 있었습니다.

PM님이 언급해주신 Parcelable은 저는 인텐트에 data class 전달할 때 사용해봤던 것 같은데 persistent하게 저장할 때는 어떻게 하는지는 잘 모르겠네요ㅠ 구글링 더 해봐야할 듯 합니다.

SharedPreference에 json string을 저장하는 방식으로 진행하신다면 참고가 되실만한 [링크1](https://stackoverflow.com/a/39385907), [링크2](https://85chong.tistory.com/29)입니다.

2021-01-04 15:11 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/model/UserInfo.kt
> +object UserInfoConstants {
만약 DI를 통해 sharedpreference 주입받고 json 형식의 String으로 저장하게 된다면 불필요한? 상수들이 되지 않을까 싶습니다.

2021-01-04 16:02 UTC, flux1126 commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/model/UserInfo.kt
> +class UserInfo(context: Context) {
DI를 통해 주입받는 방법이 훨씬 나아보입니다!

2021-01-04 16:04 UTC, flux1126 commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/model/UserInfo.kt
> +            editor.putInt(USER_ID, userDto.user_id)
처음에 Parcelable을 사용할까하다가 Kotlin으로 Android 개발할 때는 한번도 안 써봐서 고민했는데, PM님 말 들으니 Parcelable로 직렬화하는 방법이 훨씬 좋은 것 같습니다!

2021-01-04 16:05 UTC, flux1126 commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/model/UserInfo.kt
> +class UserInfo(context: Context) {
제가 빨리 Repository의 함수로 바꿔서 Review re-request 드리겠습니다.

2021-01-06 15:49 UTC, flux1126 commented
UserRepository에 다른 사람의 정보를 제공하는 getUserInfo() 함수와 자신의 정보를 제공하는 getMyInfo() 함수를 만들어보았습니다. rxjava 관련해서 혹시 잘못된 점이 있다면 지적해주시면 정말 감사드리겠습니다. 처음에는 Parcelable을 이용하고자 하였으나, 거듭된 조사 끝에 SharedPreferences는 Parcelable과 호환이 안 된다는 사실을 구글링으로 깨닫고 Gson과 Json을 이용한 방법으로 구현하였습니다.

@jusjinuk @sanggggg

2021-01-06 17:49 UTC, jusjinuk requested changes
수고하셨습니다. 부족해보이는 부분 코멘트 답니다!

2021-01-06 17:49 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/repo/UserRepository.kt
> +class UserRepository(val sp: SharedPreferences, val service: UserService) {
Koin에 Repository modulde도 같은 PR에 추가해주시면 감사드리겠습니다.

2021-01-06 17:49 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/repo/UserRepository.kt
> +        val json = sp.getString("user_info", null)
"user_info"는 companion object의 const val로 빼던지 해서 USER_INFO라고 상수화했면 좋겠네요.(오타 방지)

2021-01-06 17:49 UTC, jusjinuk commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/repo/UserRepository.kt
> +        } else { // load from network
load from network case엔 sharedpreference에 쓰기만 하고 결과를 리턴해주지 않네요. userDto 리턴이 필요해보입니다.

2021-01-06 18:04 UTC, flux1126 commented on PodoMarket/app/src/main/java/com/android/example/podomarket/data/repo/UserRepository.kt
> +        } else { // load from network
요 부분은 if/else 문으로 분기하기 전에 선언한 `val userDto` 변수를 마지막에 한번에 return 해주는 방식으로 구현했습니다!

2021-01-06 18:12 UTC, flux1126 commented
리뷰해주신 내용 모두 반영 완료했습니다!
혹시 conlfict가 생길 수 있으니, main branch로 rebase하고 force push까지 완료했습니다.
재검토해주시고 merge해주시면 감사하겠습니다.

2021-01-07 15:19 UTC, jusjinuk approved these changes

2021-01-07 15:20 UTC, merged